set -ex \
&& myapps='curl git htop man unzip vim wget telnetd apt-utils locate logrotate monit ssh sudo' \
&& apt update -yqq \
&& apt-get install -yqq --no-install-recommends software-properties-common \
&& echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections \
&& add-apt-repository -y ppa:webupd8team/java \
&& add-apt-repository -y ppa:deadsnakes/ppa \
&& apt-get update -yqq \
&& apt-get upgrade -yqq \
&& apt-get install -yqq --no-install-recommends \
    $myapps \
    build-essential \
    default-libmysqlclient-dev \
    python3.7 python3-pip python3-dev python3-virtualenv \
    oracle-java8-installer \
    erl rabbitmq-server \
    rsync \
&& useradd -ms /bin/bash -d /usr/local/airflow airflow \
&& pip3 install -U pip setuptools wheel \
&& pip install 'redis>=2.10.5,<3' \
&& pip3 install awscli --upgrade --user
&& pip install apache-airflow[crypto,celery,postgres,hive,jdbc,mysql,ssh,s3,rabbitmq,slack,google_auth,password] 
